version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bledor-dbase
    restart: unless-stopped
    environment:
      POSTGRES_USER: bledor
      POSTGRES_PASSWORD: bledor_password
      POSTGRES_DB: bledor_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api-go:
    build:
      context: ./backend-go
    container_name: bledor-go-api
    restart: unless-stopped
    environment:
      PORT: "8080"
      CORS_ORIGIN: "http://localhost:3000"
      DATABASE_URL: "postgresql://bledor:bledor_password@db:5432/bledor_db?sslmode=disable"
    depends_on:
      - db
    ports:
      - "8080:8080"
    profiles:
      - go-api

volumes:
  db_data:
